/**
 * Indian Stock Universe
 *
 * Yahoo Finance NSE symbols.
 *
 * This is intentionally kept as a plain string[]
 * so it can be safely imported by API routes,
 * services, and future market scanners.
 */

export const INDIAN_STOCK_UNIVERSE: string[] = [
  // ==============================
  // NIFTY 50
  // ==============================

  "ADANIENT.NS",
  "ADANIPORTS.NS",
//   "APOLLOHOSP.NS",
//   "ASIANPAINT.NS",
  "AXISBANK.NS",
//   "BAJAJ-AUTO.NS",
//   "BAJFINANCE.NS",
//   "BAJAJFINSV.NS",
//   "BEL.NS",
//   "BHARTIARTL.NS",
//   "CIPLA.NS",
  "COALINDIA.NS",
//   "DRREDDY.NS",
//   "EICHERMOT.NS",
  "ETERNAL.NS",
//   "GRASIM.NS",
//   "HCLTECH.NS",
  "HDFCBANK.NS",
//   "HDFCLIFE.NS",
//   "HEROMOTOCO.NS",
//   "HINDALCO.NS",
//   "HINDUNILVR.NS",
//   "ICICIBANK.NS",
//   "INDUSINDBK.NS",
//   "INFY.NS",
//   "ITC.NS",
//   "JIOFIN.NS",
  "JSWSTEEL.NS",
  "KOTAKBANK.NS",
//   "LT.NS",
//   "M&M.NS",
//   "MARUTI.NS",
//   "MAXHEALTH.NS",
//   "NESTLEIND.NS",
//   "NTPC.NS",
//   "ONGC.NS",
//   "POWERGRID.NS",
  "RELIANCE.NS",
  "SBILIFE.NS",
  "SBIN.NS",
//   "SHRIRAMFIN.NS",
//   "SUNPHARMA.NS",
//   "TATACONSUM.NS",
  "TATAMOTORS.NS",
  "TATASTEEL.NS",
  "TCS.NS",
//   "TECHM.NS",
//   "TITAN.NS",
//   "TRENT.NS",
//   "ULTRACEMCO.NS",
//   "WIPRO.NS",

  // ==============================
  // ADDITIONAL LARGE / MID CAP
  // ==============================

//   "ABB.NS",
//   "ADANIGREEN.NS",
//   "ADANIPOWER.NS",
//   "AMBUJACEM.NS",
//   "AUROPHARMA.NS",
//   "BANKBARODA.NS",
//   "BANKINDIA.NS",
//   "BANDHANBNK.NS",
//   "BHEL.NS",
//   "BIOCON.NS",
//   "BOSCHLTD.NS",
//   "CANBK.NS",
//   "CGPOWER.NS",
//   "CHOLAFIN.NS",
//   "COLPAL.NS",
//   "CONCOR.NS",
//   "CUMMINSIND.NS",
//   "DABUR.NS",
//   "DALBHARAT.NS",
//   "DLF.NS",
//   "DMART.NS",
//   "EXIDEIND.NS",
//   "FEDERALBNK.NS",
//   "GAIL.NS",
//   "GODREJCP.NS",
//   "GODREJPROP.NS",
//   "HAL.NS",
//   "HAVELLS.NS",
//   "ICICIPRULI.NS",
//   "IDFCFIRSTB.NS",
//   "INDHOTEL.NS",
//   "INDIANB.NS",
//   "INDIGO.NS",
//   "INDUSTOWER.NS",
//   "IOC.NS",
//   "IRCTC.NS",
//   "IRFC.NS",
//   "JINDALSTEL.NS",
//   "JUBLFOOD.NS",
//   "LICI.NS",
//   "LODHA.NS",
//   "LUPIN.NS",
//   "MARICO.NS",
//   "MOTHERSON.NS",
//   "MPHASIS.NS",
//   "MUTHOOTFIN.NS",
//   "NAUKRI.NS",
//   "NMDC.NS",
//   "OFSS.NS",
//   "OIL.NS",
//   "PAGEIND.NS",
//   "PATANJALI.NS",
//   "PAYTM.NS",
//   "PERSISTENT.NS",
//   "PETRONET.NS",
//   "PFC.NS",
//   "PIDILITIND.NS",
//   "PIIND.NS",
//   "POLYCAB.NS",
//   "PPLPHARMA.NS",
//   "RECLTD.NS",
//   "SAIL.NS",
//   "SHREECEM.NS",
//   "SIEMENS.NS",
//   "SRF.NS",
//   "TATACOMM.NS",
//   "TATAELXSI.NS",
//   "TORNTPHARM.NS",
//   "TORNTPOWER.NS",
//   "TVSMOTOR.NS",
//   "UNIONBANK.NS",
//   "UNITDSPR.NS",
//   "VBL.NS",
//   "VEDL.NS",
//   "VOLTAS.NS",
//   "YESBANK.NS",
//   "ZOMATO.NS",
];